import * as stylex from "@stylexjs/stylex";
import { tokens } from "../../lib/styles/tokens.stylex";

export const styles = stylex.create({
  shell: {
    maxWidth: "64rem",
  },
  heroRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "1rem",
  },
  attackerDefenderGrid: {
    marginBottom: "1.5rem",
    display: "grid",
    gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
    gap: "1rem",
    "@media (min-width: 48rem)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  panelTitle: {
    marginBottom: "0.75rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    letterSpacing: "0.05em",
    color: tokens.tx40,
    textTransform: "uppercase",
  },
  loadingWrap: {
    marginTop: "0.5rem",
    display: "flex",
    justifyContent: "center",
  },
  pokeballSm: {
    height: "1.5rem",
    width: "1.5rem",
  },
  pokeballMd: {
    height: "2rem",
    width: "2rem",
  },
  errorText: {
    marginTop: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.pokemonRed,
  },
  levelRow: {
    marginTop: "1rem",
    marginBottom: "0.5rem",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  levelRowDef: {
    marginTop: "0.75rem",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  levelLabel: {
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx40,
  },
  levelInput: {
    width: "4rem",
    borderRadius: "0.5rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "0.5rem",
    paddingBlock: "0.25rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    outlineStyle: "none",
    ":focus": {
      borderColor: `color-mix(in srgb, ${tokens.accent} 50%, transparent)`,
    },
  },
  natureItemGrid: {
    marginBottom: "0.75rem",
    display: "grid",
    gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
    gap: "0.5rem",
    "@media (min-width: 40rem)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  evWrap: {
    marginBottom: "0.75rem",
  },
  moveFilterWrap: {
    marginBottom: "0.5rem",
  },
  moveFilter: {
    width: "100%",
    borderRadius: "0.5rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "0.75rem",
    paddingBlock: "0.375rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx70,
    outlineStyle: "none",
    "::placeholder": {
      color: tokens.ph30,
    },
    ":focus": {
      borderColor: `color-mix(in srgb, ${tokens.accent} 50%, transparent)`,
    },
  },
  moveGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
    gap: "0.375rem",
    "@media (min-width: 40rem)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  moveButton: {
    display: "flex",
    width: "100%",
    cursor: "pointer",
    alignItems: "center",
    gap: "0.375rem",
    borderRadius: "0.5rem",
    borderWidth: 1,
    borderStyle: "solid",
    paddingInline: "0.625rem",
    paddingBlock: "0.5rem",
    textAlign: "left",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
  },
  moveButtonSelected: {
    borderColor: tokens.accent,
    backgroundColor: `color-mix(in srgb, ${tokens.accent} 10%, transparent)`,
    color: tokens.txStrong,
  },
  moveButtonIdle: {
    borderColor: tokens.bd4,
    backgroundColor: tokens.surf2,
    color: tokens.tx60,
  },
  moveName: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  movePower: {
    color: tokens.tx30,
  },
  dropdownWide: {
    marginTop: "0.75rem",
    marginBottom: "0.75rem",
    maxWidth: "20rem",
  },
  dropdownMax: {
    marginBottom: "0.75rem",
    maxWidth: "20rem",
  },
  statGrid: {
    marginTop: "0.75rem",
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "0.375rem",
    textAlign: "center",
  },
  statTile: {
    borderRadius: "0.5rem",
    backgroundColor: tokens.surf3,
    paddingInline: "0.5rem",
    paddingBlock: "0.375rem",
  },
  statLabel: {
    fontSize: "10px",
    color: tokens.tx40,
  },
  statValue: {
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
  },
  panelMb6: {
    marginBottom: "1.5rem",
  },
  panelMt6: {
    marginTop: "1.5rem",
  },
  conditionsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "flex-end",
    gap: "0.75rem",
  },
  ddW36: {
    width: "9rem",
  },
  ddW44: {
    width: "11rem",
  },
  ddW52: {
    width: "13rem",
  },
  critLabel: {
    display: "flex",
    cursor: "pointer",
    alignItems: "center",
    gap: "0.5rem",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "0.75rem",
    paddingBlock: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 600,
    color: tokens.tx60,
  },
  critCheckbox: {
    accentColor: tokens.accent,
    height: "0.875rem",
    width: "0.875rem",
  },
  conditionsNote: {
    marginTop: "0.75rem",
    fontSize: "11px",
    color: tokens.tx40,
  },
  loadingPanel: {
    display: "flex",
    justifyContent: "center",
    paddingBlock: "2rem",
  },
  errorPanel: {
    paddingBlock: "2rem",
    textAlign: "center",
  },
  errorMessage: {
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    color: tokens.muted,
  },
  retryButton: {
    marginTop: "1rem",
    cursor: "pointer",
    borderRadius: "0.75rem",
    borderWidth: 0,
    backgroundColor: tokens.accent,
    paddingInline: "1rem",
    paddingBlock: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 600,
    color: tokens.onAccent,
    ":hover": {
      backgroundColor: `color-mix(in srgb, ${tokens.accent} 80%, transparent)`,
    },
  },
  prompt: {
    marginBottom: "1rem",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd6,
    backgroundColor: tokens.surf2,
    padding: "0.75rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx50,
  },
  noMovesPanel: {
    paddingBlock: "2rem",
    textAlign: "center",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    color: tokens.tx40,
  },
  noDamagePanel: {
    textAlign: "center",
    color: tokens.tx50,
  },
  resultHeader: {
    marginBottom: "1.25rem",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.75rem",
  },
  resultTitle: {
    fontSize: "1.25rem",
    lineHeight: "calc(1.75 / 1.25)",
    fontWeight: 700,
  },
  resultKoBadge: {
    borderRadius: "9999px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${tokens.accent} 30%, transparent)`,
    backgroundColor: `color-mix(in srgb, ${tokens.accent} 20%, transparent)`,
    color: tokens.accent,
    paddingInline: "0.75rem",
    paddingBlock: "0.375rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 900,
    letterSpacing: "0.025em",
    textTransform: "uppercase",
  },
  resultBody: {
    marginBottom: "1.5rem",
  },
  hpLabels: {
    marginBottom: "0.25rem",
    display: "flex",
    justifyContent: "space-between",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx40,
  },
  hpTrack: {
    position: "relative",
    height: "1rem",
    overflow: "hidden",
    borderRadius: "9999px",
    backgroundColor: tokens.surf6,
  },
  hpFillMax: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    borderRadius: "9999px",
    backgroundColor: `color-mix(in srgb, ${tokens.accent} 40%, transparent)`,
  },
  hpFillMin: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    borderRadius: "9999px",
    backgroundColor: tokens.accent,
  },
  damageTotal: {
    marginTop: "0.75rem",
    textAlign: "center",
    fontSize: "1.5rem",
    lineHeight: "calc(2 / 1.5)",
    fontWeight: 900,
  },
  damageHp: {
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    fontWeight: 400,
    color: tokens.tx40,
  },
  critRange: {
    marginTop: "0.5rem",
    textAlign: "center",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx40,
  },
  resultStats: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "0.75rem",
    "@media (min-width: 48rem)": {
      gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    },
  },
  resultStatTile: {
    borderRadius: "1rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd4,
    backgroundColor: tokens.surf2,
    padding: "0.75rem",
    textAlign: "center",
  },
  resultStatLabel: {
    fontSize: "10px",
    color: tokens.tx40,
    textTransform: "uppercase",
  },
  resultStatValue: {
    marginTop: "0.25rem",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    fontWeight: 700,
  },
  resultBestMoves: {
    marginTop: "1.5rem",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.bd6,
    paddingTop: "1.25rem",
  },
  bestMovesTitle: {
    marginBottom: "1rem",
    fontSize: "1.125rem",
    lineHeight: "calc(1.75 / 1.125)",
    fontWeight: 700,
  },
  bestMovesList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  bestMoveButton: {
    display: "flex",
    width: "100%",
    cursor: "pointer",
    alignItems: "center",
    gap: "0.75rem",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    paddingInline: "0.75rem",
    paddingBlock: "0.625rem",
    textAlign: "left",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    transitionProperty:
      "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    transitionDuration: "150ms",
  },
  bestMoveSelected: {
    borderColor: tokens.accent,
    backgroundColor: `color-mix(in srgb, ${tokens.accent} 10%, transparent)`,
  },
  bestMoveIdle: {
    borderColor: tokens.bd6,
    backgroundColor: tokens.surf2,
    ":hover": {
      backgroundColor: tokens.surf5,
    },
  },
  bestMoveName: {
    width: "9rem",
    flexShrink: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: 600,
    color: tokens.tx80,
  },
  bestMoveRange: {
    flexShrink: 0,
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx40,
  },
  bestMoveTrack: {
    position: "relative",
    height: "0.5rem",
    minWidth: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflow: "hidden",
    borderRadius: "9999px",
    backgroundColor: tokens.surf6,
  },
  bestMoveFill: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    borderRadius: "9999px",
    backgroundColor: `color-mix(in srgb, ${tokens.accent} 50%, transparent)`,
  },
  koBadge: {
    flexShrink: 0,
    borderRadius: "9999px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${tokens.accent} 30%, transparent)`,
    backgroundColor: `color-mix(in srgb, ${tokens.accent} 20%, transparent)`,
    color: tokens.accent,
    paddingInline: "0.5rem",
    paddingBlock: "0.125rem",
    fontSize: "10px",
    fontWeight: 900,
    whiteSpace: "nowrap",
    textTransform: "uppercase",
  },
  bestMovesFooter: {
    marginTop: "0.75rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx40,
  },
  selectedCard: {
    marginTop: "1rem",
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    borderRadius: "0.75rem",
    backgroundColor: tokens.surf2,
    padding: "0.75rem",
    textDecorationLine: "none",
    transitionProperty:
      "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    transitionDuration: "150ms",
    ":hover": {
      backgroundColor: tokens.surf5,
    },
  },
  selectedCardImage: {
    height: "3.5rem",
    width: "3.5rem",
    objectFit: "contain",
  },
  selectedCardName: {
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    fontWeight: 700,
    color: tokens.text,
  },
  selectedCardTypes: {
    marginTop: "0.25rem",
    display: "flex",
    gap: "0.25rem",
  },
});
