import * as stylex from "@stylexjs/stylex";
import { motion } from "../../lib/styles/motion.stylex";
import { tokens } from "../../lib/styles/tokens.stylex";

export const styles = stylex.create({
  heroRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "1rem",
  },
  accent: {
    color: tokens.accent,
  },
  pickGrid: {
    marginBottom: "2rem",
    display: "grid",
    gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
    gap: "1rem",
    "@media (min-width: 48rem)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  panelP4: {
    padding: "1rem",
    "@media (min-width: 48rem)": {
      padding: "1rem",
    },
  },
  slotLabel: {
    marginBottom: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    letterSpacing: "0.05em",
    color: tokens.tx40,
    textTransform: "uppercase",
  },
  loadingRow: {
    marginTop: "0.75rem",
    display: "flex",
    justifyContent: "center",
  },
  pokeball: {
    height: "1.5rem",
    width: "1.5rem",
  },
  errorBox: {
    marginBottom: "1.5rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: `color-mix(in srgb, ${tokens.pokemonRed} 30%, transparent)`,
    borderRadius: "0.75rem",
    backgroundColor: `color-mix(in srgb, ${tokens.pokemonRed} 10%, transparent)`,
    paddingInline: "1rem",
    paddingBlock: "0.75rem",
    textAlign: "center",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.pokemonRed,
  },
  vsGrid: {
    position: "relative",
    marginBottom: "1.5rem",
    display: "grid",
    gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
    gap: "1rem",
    "@media (min-width: 48rem)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  vsBadge: {
    position: "absolute",
    top: "50%",
    left: "50%",
    zIndex: 10,
    display: "none",
    height: "3rem",
    width: "3rem",
    translate: "-50% -50%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "9999px",
    borderWidth: 4,
    borderStyle: "solid",
    borderColor: tokens.bg,
    fontWeight: 900,
    color: tokens.onAccent,
    backgroundColor: tokens.accent,
    boxShadow:
      "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
    "@media (min-width: 48rem)": {
      display: "flex",
    },
  },
  cardLink: {
    marginBottom: "1.25rem",
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    borderRadius: "0.75rem",
    padding: "0.5rem",
    textDecorationLine: "none",
    transitionProperty:
      "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    ":hover": {
      backgroundColor: tokens.surf5,
    },
  },
  artwork: {
    height: "5rem",
    width: "5rem",
    objectFit: "contain",
    filter: "drop-shadow(0 9px 7px rgb(0 0 0 / 0.1))",
  },
  name: {
    fontSize: "1.25rem",
    lineHeight: "calc(1.75 / 1.25)",
    fontWeight: 900,
    color: tokens.text,
  },
  idText: {
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx40,
  },
  typeRow: {
    marginTop: "0.375rem",
    display: "flex",
    gap: "0.25rem",
  },
  stats: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  total: {
    borderTopWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd6,
    paddingTop: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    color: tokens.tx60,
  },
  emptySlot: {
    display: "flex",
    minHeight: "16rem",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    color: tokens.tx30,
  },
  panelMb6: {
    marginBottom: "1.5rem",
  },
  sectionTitle: {
    marginBottom: "1rem",
    fontSize: "1.125rem",
    lineHeight: "calc(1.75 / 1.125)",
    fontWeight: 700,
  },
  radarWrap: {
    marginInline: "auto",
    width: "100%",
    maxWidth: "24rem",
  },
  diffs: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
  },
  diffRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  },
  diffLabel: {
    width: "3rem",
    textAlign: "right",
    fontSize: "10px",
    fontWeight: 700,
    color: tokens.tx45,
  },
  diffValueLeft: {
    width: "1.75rem",
    textAlign: "right",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
  },
  diffValueRight: {
    width: "1.75rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
  },
  diffTrack: {
    display: "flex",
    height: "0.5rem",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflow: "hidden",
    borderRadius: "9999px",
    backgroundColor: tokens.surf4,
  },
  diffFill: {
    height: "100%",
  },
  diffDelta: {
    width: "2.5rem",
    textAlign: "right",
    fontSize: "10px",
    fontWeight: 700,
  },
  diffPos: {
    color: "#4ade80",
  },
  diffNeg: {
    color: "#f87171",
  },
  diffMuted: {
    color: tokens.muted,
  },
});
