import * as stylex from "@stylexjs/stylex";
import { motion } from "../lib/styles/motion.stylex";
import { tokens } from "../lib/styles/tokens.stylex";

const pulse = stylex.keyframes({
  "50%": { opacity: 0.5 },
});

export const styles = stylex.create({
  root: {
    position: "relative",
    minHeight: "calc(100vh - 73px)",
  },
  glowLayer: {
    pointerEvents: "none",
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    overflow: "hidden",
  },
  glowRed: {
    position: "absolute",
    top: "-6rem",
    right: "-6rem",
    height: "24rem",
    width: "24rem",
    borderRadius: "9999px",
    filter: "blur(64px)",
    backgroundColor: `color-mix(in srgb, ${tokens.pokemonRed} 5%, transparent)`,
  },
  glowAccent: {
    position: "absolute",
    bottom: "-8rem",
    left: "-8rem",
    height: "31.25rem",
    width: "31.25rem",
    borderRadius: "9999px",
    filter: "blur(64px)",
    backgroundColor: `color-mix(in srgb, ${tokens.accent} 5%, transparent)`,
  },
  container: {
    position: "relative",
    marginInline: "auto",
    maxWidth: "80rem",
    paddingInline: {
      default: "1rem",
      "@media (min-width: 48rem)": "1.5rem",
    },
  },
  hero: {
    paddingTop: {
      default: "2.5rem",
      "@media (min-width: 48rem)": "3.5rem",
    },
    paddingBottom: "1.5rem",
    textAlign: "center",
  },
  statsBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    marginBottom: "1.25rem",
    borderRadius: "9999px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "1rem",
    paddingBlock: "0.375rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: tokens.tx60,
  },
  pulseDot: {
    height: "0.5rem",
    width: "0.5rem",
    borderRadius: "9999px",
    backgroundColor: tokens.pokemonGreen,
    animationName: pulse,
    animationDuration: "2s",
    animationTimingFunction: "cubic-bezier(0.4, 0, 0.6, 1)",
    animationIterationCount: "infinite",
  },
  heroTitle: {
    marginBottom: "0.75rem",
    fontSize: {
      default: "2.25rem",
      "@media (min-width: 48rem)": "3.75rem",
    },
    lineHeight: {
      default: "calc(2.5 / 2.25)",
      "@media (min-width: 48rem)": "1",
    },
    fontWeight: 900,
    letterSpacing: "-0.025em",
    color: tokens.text,
  },
  heroGradient: {
    backgroundImage: `linear-gradient(to right, ${tokens.pokemonRed}, ${tokens.pokemonYellow}, ${tokens.accent})`,
    backgroundClip: "text",
    color: "transparent",
  },
  heroText: {
    marginInline: "auto",
    marginBottom: "1.25rem",
    maxWidth: "42rem",
    fontSize: {
      default: "1rem",
      "@media (min-width: 48rem)": "1.125rem",
    },
    lineHeight: {
      default: "calc(1.5 / 1)",
      "@media (min-width: 48rem)": "calc(1.75 / 1.125)",
    },
    color: tokens.muted,
  },
  heroKbd: {
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
  },
  heroActions: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "0.5rem",
  },
  heroIcon: {
    height: "1rem",
    width: "1rem",
    flexShrink: 0,
  },
  heroBtn: {
    display: "inline-flex",
    cursor: "pointer",
    alignItems: "center",
    gap: "0.5rem",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    paddingInline: "1rem",
    paddingBlock: "0.5rem",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    fontWeight: 600,
    transitionProperty: "all",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  heroBtnMuted: {
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    color: tokens.tx70,
    ":hover": {
      backgroundColor: tokens.surf10,
      color: tokens.txStrong,
    },
  },
  heroBtnOutline: {
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    color: tokens.tx70,
    ":hover": {
      color: tokens.txStrong,
    },
  },
  heroBtnActive: {
    backgroundColor: `color-mix(in srgb, ${tokens.pokemonYellow} 20%, transparent)`,
    borderColor: `color-mix(in srgb, ${tokens.pokemonYellow} 40%, transparent)`,
    color: tokens.yellowText,
  },
  recentSection: {
    marginBottom: "1.5rem",
  },
  recentTitle: {
    marginBottom: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: tokens.tx40,
  },
  recentRow: {
    display: "flex",
    gap: "0.5rem",
    overflowX: "auto",
    paddingBottom: "0.5rem",
  },
  recentCard: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    gap: "0.5rem",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd6,
    backgroundColor: tokens.surf3,
    paddingInline: "0.75rem",
    paddingBlock: "0.5rem",
    textDecorationLine: "none",
    transitionProperty: "all",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    ":hover": {
      borderColor: tokens.bd20,
    },
  },
  recentImage: {
    height: "2rem",
    width: "2rem",
    objectFit: "contain",
  },
  recentName: {
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 600,
    color: tokens.tx70,
  },
  filterBar: {
    position: "sticky",
    top: "4.25rem",
    zIndex: 40,
    marginBottom: "1.5rem",
    borderRadius: "1rem",
    borderWidth: 1,
    borderStyle: "solid",
    paddingInline: {
      default: "1rem",
      "@media (min-width: 48rem)": "1.5rem",
    },
    paddingBlock: "0.75rem",
    backdropFilter: "blur(12px)",
    backgroundColor: `color-mix(in srgb, ${tokens.bg} 92%, transparent)`,
    borderColor: tokens.border,
  },
  filterInner: {
    display: "flex",
    flexDirection: {
      default: "column",
      "@media (min-width: 48rem)": "row",
    },
    alignItems: {
      default: "stretch",
      "@media (min-width: 48rem)": "center",
    },
    gap: "0.75rem",
  },
  searchWrap: {
    position: "relative",
    maxWidth: "28rem",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  searchIconWrap: {
    pointerEvents: "none",
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    display: "flex",
    alignItems: "center",
    paddingLeft: "0.75rem",
  },
  searchIcon: {
    height: "1rem",
    width: "1rem",
    color: tokens.tx30,
  },
  searchInput: {
    width: "100%",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingBlock: "0.625rem",
    paddingRight: "0.75rem",
    paddingLeft: "2.5rem",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    color: tokens.txStrong,
    outlineStyle: "none",
    ":focus": {
      borderColor: `color-mix(in srgb, ${tokens.accent} 50%, transparent)`,
    },
    "::placeholder": {
      color: tokens.ph30,
    },
  },
  filterControls: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.5rem",
  },
  filtersToggle: {
    display: {
      default: "inline-block",
      "@media (min-width: 48rem)": "none",
    },
    cursor: "pointer",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "0.75rem",
    paddingBlock: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 600,
    color: tokens.tx70,
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  resultCount: {
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx40,
  },
  sortSelect: {
    cursor: "pointer",
    borderRadius: "0.5rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "0.5rem",
    paddingBlock: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx70,
    outlineStyle: "none",
    ":focus": {
      borderColor: `color-mix(in srgb, ${tokens.accent} 50%, transparent)`,
    },
  },
  filterHint: {
    marginTop: "0.25rem",
    fontSize: "10px",
    color: tokens.muted,
  },
  filterRows: {
    marginTop: "0.75rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  filterRowsCollapsed: {
    display: {
      default: "none",
      "@media (min-width: 48rem)": "flex",
    },
  },
  chipRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.375rem",
  },
  loadingText: {
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    color: tokens.muted,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 40rem)": "repeat(3, minmax(0, 1fr))",
      "@media (min-width: 48rem)": "repeat(4, minmax(0, 1fr))",
      "@media (min-width: 64rem)": "repeat(5, minmax(0, 1fr))",
    },
    gap: {
      default: "0.75rem",
      "@media (min-width: 48rem)": "1rem",
    },
    paddingBottom: "2rem",
  },
  formsPanel: {
    right: 0,
    maxHeight: "16rem",
    borderRadius: "0.75rem",
    padding: "0.375rem",
  },
  cardImageWrap: {
    position: "relative",
    display: "flex",
    aspectRatio: "1 / 1",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: "1.25rem",
  },
  cardGlow: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    opacity: 0.4,
  },
  cardImage: {
    position: "relative",
    zIndex: 10,
    objectFit: "contain",
    filter: "drop-shadow(0 25px 25px rgb(0 0 0 / 0.15))",
    transitionProperty: "transform, translate, scale, rotate",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: "500ms",
    translate: "0 0",
    [stylex.when.ancestor(":hover")]: {
      translate: "0 -0.25rem",
      scale: 1.1,
    },
  },
  cardImageActive: {
    height: "100%",
    width: "100%",
  },
  cardImageFit: {
    maxHeight: "100%",
    maxWidth: "100%",
  },
  idBadge: {
    position: "absolute",
    top: "0.625rem",
    left: "0.625rem",
    borderRadius: "0.375rem",
    backgroundColor: tokens.scrim35,
    paddingInline: "0.5rem",
    paddingBlock: "0.125rem",
    fontSize: "10px",
    fontWeight: 900,
    letterSpacing: "0.05em",
    backdropFilter: "blur(8px)",
  },
  favBtn: {
    position: "absolute",
    top: "0.625rem",
    right: "0.625rem",
    zIndex: 20,
    display: "flex",
    height: "2rem",
    width: "2rem",
    cursor: "pointer",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "0.5rem",
    borderWidth: 0,
    backgroundColor: tokens.scrim35,
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    backdropFilter: "blur(8px)",
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  favActive: {
    color: tokens.yellowText,
  },
  favIdle: {
    color: tokens.tx40,
    ":hover": {
      color: tokens.txStrong,
    },
  },
  formsBtn: {
    position: "absolute",
    right: "0.625rem",
    bottom: "0.625rem",
    zIndex: 20,
    cursor: "pointer",
    borderRadius: "0.375rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.scrim40,
    paddingInline: "0.5rem",
    paddingBlock: "0.125rem",
    fontSize: "10px",
    fontWeight: 700,
    color: tokens.tx80,
    backdropFilter: "blur(8px)",
    ":hover": {
      color: tokens.txStrong,
    },
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  cardBody: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.bd4,
    padding: "0.75rem",
    paddingTop: "0.5rem",
  },
  cardName: {
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    fontWeight: 700,
    color: tokens.tx85,
    transitionProperty:
      "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    [stylex.when.ancestor(":hover")]: {
      color: tokens.txStrong,
    },
  },
  typeRow: {
    marginTop: "0.375rem",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.25rem",
  },
  genBadge: {
    marginLeft: "auto",
    borderRadius: "9999px",
    paddingInline: "0.375rem",
    paddingBlock: "0.125rem",
    fontSize: "9px",
    fontWeight: 700,
    color: tokens.tx80,
  },
  formLink: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    borderRadius: "0.5rem",
    paddingInline: "0.5rem",
    paddingBlock: "0.375rem",
    textDecorationLine: "none",
    transitionProperty:
      "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    color: tokens.text,
    ":hover": {
      backgroundColor: tokens.surf5,
    },
  },
  formImage: {
    height: "2rem",
    width: "2rem",
    flexShrink: 0,
    objectFit: "contain",
  },
  formBody: {
    minWidth: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  formName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "11px",
    fontWeight: 600,
  },
  formMeta: {
    fontSize: "9px",
    color: tokens.muted,
  },
});
