import * as stylex from "@stylexjs/stylex";
import { motion } from "../../../lib/styles/motion.stylex";
import { tokens } from "../../../lib/styles/tokens.stylex";

const pulse = stylex.keyframes({
  "50%": { opacity: 0.5 },
});

const bob = stylex.keyframes({
  "0%": { transform: "translateY(0px)" },
  "50%": { transform: "translateY(-10px)" },
  "100%": { transform: "translateY(0px)" },
});

export const styles = stylex.create({
  pageRoot: {
    position: "relative",
    minHeight: "calc(100vh - 73px)",
  },
  container: {
    position: "relative",
    marginInline: "auto",
    maxWidth: "72rem",
    paddingInline: "1rem",
    paddingBlock: "1.5rem",
    "@media (min-width: 48rem)": {
      paddingInline: "1.5rem",
    },
  },
  topBar: {
    marginBottom: "1.5rem",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.75rem",
  },
  backLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "1rem",
    paddingBlock: "0.5rem",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    fontWeight: 600,
    color: tokens.tx60,
    textDecorationLine: "none",
    transitionProperty: "all",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    ":hover": {
      color: tokens.txStrong,
    },
  },
  navButtons: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  siblingLink: {
    display: "flex",
    height: "2.25rem",
    width: "2.25rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    color: tokens.tx50,
    textDecorationLine: "none",
    ":hover": {
      color: tokens.txStrong,
    },
  },
  heroGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
    gap: "2rem",
    "@media (min-width: 64rem)": {
      gridTemplateColumns: "1fr 1.3fr",
    },
  },
  pulse: {
    animationName: pulse,
    animationDuration: "2s",
    animationTimingFunction: "cubic-bezier(0.4, 0, 0.6, 1)",
    animationIterationCount: "infinite",
  },
  skeletonHero: {
    aspectRatio: "1 / 1",
    borderRadius: "1.5rem",
    backgroundColor: tokens.surf3,
  },
  skeletonSide: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  skeletonTall: {
    height: "16rem",
    borderRadius: "1.5rem",
    backgroundColor: tokens.surf3,
  },
  skeletonShort: {
    height: "10rem",
    borderRadius: "1.5rem",
    backgroundColor: tokens.surf3,
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
    alignItems: "start",
    gap: "2rem",
    "@media (min-width: 64rem)": {
      gridTemplateColumns: "1fr 1.35fr",
    },
  },
  stickyCol: {
    "@media (min-width: 64rem)": {
      position: "sticky",
      top: "6rem",
    },
  },
  artCard: {
    position: "relative",
    overflow: "hidden",
    borderRadius: "1.5rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd6,
  },
  artStage: {
    position: "relative",
    display: "flex",
    aspectRatio: "1 / 1",
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem",
  },
  artGlow: {
    position: "absolute",
    height: "14rem",
    width: "14rem",
    borderRadius: "9999px",
    opacity: 0.15,
  },
  heroImage: {
    position: "relative",
    zIndex: 10,
    width: "100%",
    maxWidth: "20rem",
    objectFit: "contain",
    filter: "drop-shadow(0 25px 25px rgb(0 0 0 / 0.15))",
    animationName: bob,
    animationDuration: "3s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
  },
  chipBar: {
    position: "absolute",
    top: "1rem",
    left: "1rem",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.375rem",
  },
  chip: {
    cursor: "pointer",
    borderRadius: "9999px",
    borderWidth: 1,
    borderStyle: "solid",
    paddingInline: "0.625rem",
    paddingBlock: "0.25rem",
    fontSize: "10px",
    fontWeight: 900,
    textTransform: "uppercase",
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  chipActive: {
    color: tokens.btnFg,
    backgroundColor: tokens.btnBg,
    borderColor: tokens.btnBg,
  },
  chipInactive: {
    borderColor: tokens.bd10,
    backgroundColor: tokens.scrim40,
    color: tokens.tx60,
  },
  chipFav: {
    backgroundColor: `color-mix(in srgb, ${tokens.pokemonYellow} 20%, transparent)`,
    borderColor: `color-mix(in srgb, ${tokens.pokemonYellow} 40%, transparent)`,
    color: tokens.yellowText,
  },
  chipLink: {
    textDecorationLine: "none",
    transitionProperty:
      "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    ":hover": {
      color: tokens.txStrong,
    },
  },
  badgeCol: {
    position: "absolute",
    bottom: "1rem",
    right: "1rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
  },
  rankBadge: {
    borderRadius: "9999px",
    paddingInline: "0.75rem",
    paddingBlock: "0.25rem",
    fontSize: "10px",
    fontWeight: 900,
    color: tokens.onAccent,
    textTransform: "uppercase",
  },
  rankBadgeLink: {
    cursor: "pointer",
    textDecorationLine: "none",
    transitionProperty: "all",
    transitionDuration: motion.durFast,
    transitionTimingFunction: motion.easeStandard,
    ":hover": {
      scale: 1.04,
    },
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":hover": {
        scale: 1,
      },
      ":active": {
        scale: 1,
      },
    },
  },
  legendaryBadge: {
    backgroundImage: `linear-gradient(135deg, #fff8c2 0%, #ffdf4d 25%, ${tokens.pokemonYellow} 50%, ${tokens.pokemonGold} 100%)`,
    color: tokens.txNavy,
    boxShadow: `inset 0 1px 0 rgba(255, 255, 255, 0.55), 0 0 12px color-mix(in srgb, ${tokens.pokemonYellow} 45%, transparent)`,
  },
  mythicalBadge: {
    backgroundImage:
      "linear-gradient(to right, oklch(65.6% 0.241 354.308), oklch(62.7% 0.265 303.9))",
    boxShadow:
      "inset 0 1px 0 rgba(255, 255, 255, 0.45), 0 0 12px color-mix(in srgb, oklch(65.6% 0.241 354.308) 45%, transparent)",
  },
  identity: {
    marginTop: "1.25rem",
    textAlign: "center",
  },
  dexNumber: {
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    fontWeight: 700,
    letterSpacing: "0.05em",
  },
  formId: {
    marginLeft: "0.375rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.muted,
  },
  genus: {
    marginLeft: "0.5rem",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    color: tokens.muted,
  },
  dexRow: {
    marginTop: "0.5rem",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "0.375rem",
  },
  dexPill: {
    borderRadius: "9999px",
    borderWidth: 1,
    borderStyle: "solid",
    paddingInline: "0.5rem",
    paddingBlock: "0.125rem",
    fontSize: "10px",
    fontWeight: 700,
    whiteSpace: "nowrap",
    borderColor: tokens.border,
    color: tokens.muted,
  },
  name: {
    marginTop: "0.25rem",
    fontSize: "2.25rem",
    lineHeight: "calc(2.5 / 2.25)",
    fontWeight: 900,
    color: tokens.text,
    "@media (min-width: 48rem)": {
      fontSize: "3rem",
      lineHeight: "1",
    },
  },
  formNote: {
    marginTop: "0.25rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.muted,
  },
  typeRow: {
    marginTop: "0.75rem",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "0.5rem",
  },
  flavor: {
    marginTop: "1rem",
    fontSize: "0.875rem",
    lineHeight: 1.625,
    fontStyle: "italic",
    color: tokens.muted,
  },
  quickPanel: {
    marginTop: "1.25rem",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "0.5rem",
    padding: "0.75rem",
    "@media (min-width: 48rem)": {
      padding: "0.75rem",
    },
  },
  qsCell: {
    paddingBlock: "0.5rem",
    textAlign: "center",
  },
  qsCellLeft: {
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: tokens.bd6,
  },
  qsCellTop: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.bd6,
  },
  qsValue: {
    fontSize: "1.125rem",
    lineHeight: "calc(1.75 / 1.125)",
    fontWeight: 700,
  },
  qsLabel: {
    fontSize: "10px",
    letterSpacing: "0.05em",
    color: tokens.tx40,
    textTransform: "uppercase",
  },
  formsPanel: {
    marginTop: "0.75rem",
    maxWidth: "100%",
    overflow: "hidden",
    padding: "0.75rem",
    "@media (min-width: 48rem)": {
      padding: "0.75rem",
    },
  },
  formsTitle: {
    marginBottom: "0.5rem",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: tokens.muted,
  },
  formsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  formCard: {
    display: "flex",
    width: "4rem",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.25rem",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    padding: "0.375rem",
    textDecorationLine: "none",
    color: tokens.text,
    transitionProperty: "all",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
  },
  formCardActive: {
    borderColor: tokens.accent,
    backgroundColor: `color-mix(in srgb, ${tokens.accent} 10%, transparent)`,
  },
  formCardInactive: {
    borderColor: tokens.bd10,
    ":hover": {
      borderColor: tokens.bd25,
    },
  },
  formImage: {
    height: "3rem",
    width: "3rem",
    objectFit: "contain",
  },
  formLabel: {
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    overflow: "hidden",
    textAlign: "center",
    fontSize: "9px",
    lineHeight: 1.25,
    fontWeight: 600,
  },
  tabCol: {
    paddingBottom: "3rem",
  },
  tabStack: {
    display: "flex",
    flexDirection: "column",
    gap: "1.25rem",
  },
  sectionTitle: {
    marginBottom: "1rem",
    fontSize: "1.125rem",
    lineHeight: "calc(1.75 / 1.125)",
    fontWeight: 700,
  },
  sectionTitleWide: {
    marginBottom: "1.25rem",
    fontSize: "1.125rem",
    lineHeight: "calc(1.75 / 1.125)",
    fontWeight: 700,
  },
  statsTitle: {
    fontSize: "1.125rem",
    lineHeight: "calc(1.75 / 1.125)",
    fontWeight: 700,
  },
  abilityList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  abilityCard: {
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    padding: "0.75rem",
  },
  abilityHead: {
    marginBottom: "0.25rem",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  abilityName: {
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    fontWeight: 700,
  },
  hiddenBadge: {
    borderRadius: "0.25rem",
    backgroundColor: tokens.surf10,
    paddingInline: "0.375rem",
    paddingBlock: "0.125rem",
    fontSize: "9px",
    fontWeight: 700,
    color: tokens.tx50,
    textTransform: "uppercase",
  },
  abilityDesc: {
    fontSize: "0.75rem",
    lineHeight: 1.625,
    color: tokens.tx50,
  },
  twoColGrid: {
    display: "grid",
    gap: "0.5rem",
    "@media (min-width: 40rem)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  locCard: {
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd4,
    backgroundColor: tokens.surf2,
    paddingInline: "0.75rem",
    paddingBlock: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
  },
  locArea: {
    fontWeight: 600,
    color: tokens.tx80,
    textTransform: "capitalize",
  },
  locMethod: {
    marginTop: "0.125rem",
    color: tokens.tx40,
    textTransform: "capitalize",
  },
  statsHead: {
    marginBottom: "1.25rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  totalBadge: {
    display: "flex",
    height: "2.75rem",
    width: "2.75rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "9999px",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    fontWeight: 900,
  },
  chartsCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1.5rem",
  },
  radarWrap: {
    marginInline: "auto",
    width: "100%",
    maxWidth: "24rem",
  },
  barsWrap: {
    width: "100%",
    maxWidth: "28rem",
  },
  loadingWrap: {
    display: "flex",
    justifyContent: "center",
    paddingBlock: "2.5rem",
  },
  spinner: {
    height: "2rem",
    width: "2rem",
  },
  moveTabs: {
    marginBottom: "1rem",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  moveTab: {
    cursor: "pointer",
    borderRadius: "0.5rem",
    borderWidth: 0,
    paddingInline: "0.75rem",
    paddingBlock: "0.375rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    textTransform: "uppercase",
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  moveTabActive: {
    color: tokens.txStrong,
  },
  moveTabInactive: {
    backgroundColor: tokens.surf5,
    color: tokens.tx40,
  },
  moveRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd4,
    backgroundColor: tokens.surf2,
    paddingInline: "0.75rem",
    paddingBlock: "0.5rem",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
  },
  moveLevel: {
    width: "2rem",
    textAlign: "right",
    fontSize: "11px",
    fontWeight: 900,
    color: tokens.tx50,
  },
  moveName: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontWeight: 600,
    color: tokens.tx80,
  },
  moveStats: {
    fontSize: "10px",
    color: tokens.tx30,
  },
  dataGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "1rem",
    "@media (min-width: 48rem)": {
      gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    },
  },
  dataLabel: {
    fontSize: "10px",
    letterSpacing: "0.05em",
    color: tokens.tx40,
    textTransform: "uppercase",
  },
  dataValue: {
    fontWeight: 700,
  },
  capitalize: {
    textTransform: "capitalize",
  },
});
