import * as stylex from "@stylexjs/stylex";
import { motion } from "../../lib/styles/motion.stylex";
import { tokens } from "../../lib/styles/tokens.stylex";

export const styles = stylex.create({
  heroRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "1rem",
  },
  searchPanel: {
    marginBottom: "1.5rem",
    maxWidth: "36rem",
    padding: "1rem",
    "@media (min-width: 48rem)": {
      padding: "1rem",
    },
  },
  loadingRow: {
    marginTop: "0.5rem",
    display: "flex",
    justifyContent: "center",
  },
  pokeballSm: {
    height: "1.5rem",
    width: "1.5rem",
  },
  pokeballMd: {
    height: "2rem",
    width: "2rem",
  },
  errorText: {
    color: tokens.pokemonRed,
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
  },
  slotError: {
    marginTop: "0.5rem",
  },
  secondaryButton: {
    cursor: "pointer",
    borderRadius: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "0.75rem",
    paddingBlock: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 600,
    color: tokens.tx60,
    transitionProperty:
      "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    ":hover": {
      color: tokens.txStrong,
    },
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  importToggle: {
    marginTop: "0.75rem",
  },
  stack2: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  importArea: {
    marginTop: "0.75rem",
  },
  importTextarea: {
    width: "100%",
    borderRadius: "0.5rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "0.75rem",
    paddingBlock: "0.5rem",
    resize: "vertical",
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx80,
    outlineStyle: "none",
    "::placeholder": {
      color: tokens.ph25,
    },
    ":focus": {
      borderColor: `color-mix(in srgb, ${tokens.accent} 50%, transparent)`,
    },
  },
  importActions: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  accentButton: {
    backgroundColor: tokens.accent,
    cursor: "pointer",
    borderRadius: "0.75rem",
    borderWidth: 0,
    fontWeight: 600,
    color: tokens.onAccent,
    ":hover": {
      backgroundColor: `color-mix(in srgb, ${tokens.accent} 80%, transparent)`,
    },
    ":disabled": {
      opacity: 0.4,
    },
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  importButton: {
    paddingInline: "1rem",
    paddingBlock: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
  },
  shareButton: {
    paddingInline: "1rem",
    paddingBlock: "0.5rem",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
  },
  doneButton: {
    paddingInline: "1.25rem",
    paddingBlock: "0.5rem",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
  },
  hintText: {
    fontSize: "10px",
    color: tokens.tx40,
  },
  slotsGrid: {
    marginBottom: "2rem",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "0.75rem",
    "@media (min-width: 40rem)": {
      gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    },
    "@media (min-width: 48rem)": {
      gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    },
  },
  slotWrap: {
    position: "relative",
    transitionProperty: "all",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    ":hover": {
      translate: "0 -0.25rem",
    },
  },
  slotButton: {
    position: "relative",
    width: "100%",
    cursor: "pointer",
    padding: "0.75rem",
    textAlign: "center",
    "@media (min-width: 48rem)": {
      padding: "0.75rem",
    },
  },
  slotImage: {
    marginInline: "auto",
    height: "4rem",
    width: "4rem",
    objectFit: "contain",
  },
  slotName: {
    marginTop: "0.25rem",
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    color: tokens.text,
  },
  slotTypes: {
    marginTop: "0.25rem",
    display: "flex",
    justifyContent: "center",
    gap: "0.125rem",
  },
  setBadge: {
    backgroundColor: `color-mix(in srgb, ${tokens.pokemonGreen} 20%, transparent)`,
    color: tokens.pokemonGreen,
    marginTop: "0.375rem",
    display: "inline-block",
    borderRadius: "9999px",
    paddingInline: "0.5rem",
    paddingBlock: "0.125rem",
    fontSize: "9px",
    fontWeight: 700,
  },
  slotLink: {
    position: "absolute",
    top: "0.5rem",
    left: "0.5rem",
    zIndex: 10,
    display: "flex",
    height: "1.5rem",
    width: "1.5rem",
    cursor: "pointer",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "0.375rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.scrim20,
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx50,
    textDecorationLine: "none",
    ":hover": {
      color: tokens.txStrong,
    },
  },
  removeButton: {
    backgroundColor: `color-mix(in srgb, ${tokens.pokemonRed} 20%, transparent)`,
    color: tokens.pokemonRed,
    position: "absolute",
    top: "0.5rem",
    right: "0.5rem",
    zIndex: 10,
    height: "1.5rem",
    width: "1.5rem",
    cursor: "pointer",
    borderRadius: "0.375rem",
    borderWidth: 0,
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    transitionProperty:
      "color, background-color, border-color, outline-color, text-decoration-color, fill, stroke",
    transitionTimingFunction: motion.easeStandard,
    transitionDuration: motion.durFast,
    ":hover": {
      backgroundColor: `color-mix(in srgb, ${tokens.pokemonRed} 40%, transparent)`,
    },
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  emptySlot: {
    display: "flex",
    minHeight: "9rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "1.5rem",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: tokens.bd10,
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx20,
  },
  editorPanel: {
    marginBottom: "2rem",
    maxWidth: "42rem",
  },
  editorHeader: {
    marginBottom: "1rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  editorHeadLeft: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  },
  editorImage: {
    height: "3rem",
    width: "3rem",
    objectFit: "contain",
  },
  editorName: {
    fontSize: "1.125rem",
    lineHeight: "calc(1.75 / 1.125)",
    fontWeight: 700,
    color: tokens.text,
  },
  typeRow: {
    display: "flex",
    gap: "0.25rem",
  },
  loadingBox: {
    display: "flex",
    justifyContent: "center",
    paddingBlock: "2rem",
  },
  editorGrid: {
    display: "grid",
    gap: "1rem",
    "@media (min-width: 48rem)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  sectionLabel: {
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.05em",
    color: tokens.tx40,
    textTransform: "uppercase",
  },
  movesList: {
    marginTop: "0.5rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  relative: {
    position: "relative",
  },
  moveOption: {
    display: "flex",
    alignItems: "center",
    gap: "0.375rem",
  },
  moveMeta: {
    marginLeft: "auto",
    fontSize: "10px",
    color: tokens.tx30,
  },
  editorColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  buttonMt2: {
    marginTop: "0.5rem",
  },
  finalStats: {
    marginTop: "1rem",
  },
  finalStatsHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  levelButton: {
    cursor: "pointer",
    borderRadius: "9999px",
    borderWidth: 1,
    borderStyle: "solid",
    paddingInline: "0.5rem",
    paddingBlock: "0.125rem",
    fontSize: "10px",
    fontWeight: 700,
    ":active": {
      scale: motion.pressScale,
    },
    "@media (prefers-reduced-motion: reduce)": {
      ":active": {
        scale: 1,
      },
    },
  },
  levelButtonActive: {
    backgroundColor: tokens.accent,
    borderColor: tokens.accent,
    color: tokens.onAccent,
  },
  levelButtonIdle: {
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    color: tokens.tx50,
    ":hover": {
      color: tokens.txStrong,
    },
  },
  statsGrid: {
    marginTop: "0.5rem",
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: "0.375rem",
    textAlign: "center",
  },
  statCell: {
    borderRadius: "0.5rem",
    backgroundColor: tokens.surf3,
    paddingInline: "0.25rem",
    paddingBlock: "0.375rem",
  },
  statLabel: {
    fontSize: "9px",
    color: tokens.tx40,
  },
  statValue: {
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    color: tokens.text,
  },
  statBase: {
    fontSize: "9px",
    color: tokens.tx30,
  },
  coverageGrid: {
    marginBottom: "1.5rem",
    display: "grid",
    gap: "1rem",
    "@media (min-width: 48rem)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  panelTitle: {
    marginBottom: "1rem",
    fontSize: "1.125rem",
    lineHeight: "calc(1.75 / 1.125)",
    fontWeight: 700,
  },
  heatGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "0.5rem",
    "@media (min-width: 40rem)": {
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    },
  },
  tooltipWide: {
    width: "max-content",
  },
  tooltipNarrow: {
    width: "14rem",
  },
  heatCell: {
    cursor: "pointer",
    borderRadius: "0.5rem",
    borderWidth: 1,
    borderStyle: "solid",
    paddingInline: "0.5rem",
    paddingBlock: "0.5rem",
    textAlign: "center",
    fontSize: "10px",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  heatWeak: {
    backgroundColor: `color-mix(in srgb, ${tokens.pokemonRed} 20%, transparent)`,
    borderColor: `color-mix(in srgb, ${tokens.pokemonRed} 30%, transparent)`,
  },
  heatSafe: {
    backgroundColor: `color-mix(in srgb, ${tokens.pokemonGreen} 20%, transparent)`,
    borderColor: `color-mix(in srgb, ${tokens.pokemonGreen} 30%, transparent)`,
  },
  heatOk: {
    backgroundColor: tokens.surface2,
    borderColor: tokens.border,
  },
  heatTypeName: {
    display: "block",
  },
  opacity60: {
    opacity: 0.6,
  },
  coveragePanel: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  coverageHeading: {
    marginBottom: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
  sectionRed: {
    color: tokens.pokemonRed,
  },
  sectionGreen: {
    color: tokens.pokemonGreen,
  },
  coverageTypes: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.375rem",
  },
  coverageEmpty: {
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx40,
  },
  teamFooter: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.5rem",
    borderTopWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd6,
    paddingTop: "0.75rem",
  },
  teamNameInput: {
    minWidth: "7.5rem",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    borderRadius: "0.5rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd10,
    backgroundColor: tokens.surf5,
    paddingInline: "0.75rem",
    paddingBlock: "0.5rem",
    fontSize: "0.875rem",
    lineHeight: "calc(1.25 / 0.875)",
    outlineStyle: "none",
    "::placeholder": {
      color: tokens.muted,
    },
    ":focus": {
      borderColor: `color-mix(in srgb, ${tokens.accent} 50%, transparent)`,
    },
  },
  savedTitle: {
    marginBottom: "0.5rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    fontWeight: 700,
    letterSpacing: "0.05em",
    color: tokens.tx40,
    textTransform: "uppercase",
  },
  savedList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
  },
  savedItem: {
    borderRadius: "0.5rem",
    backgroundColor: tokens.surf2,
    paddingInline: "0.5rem",
    paddingBlock: "0.375rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
    color: tokens.tx60,
  },
  summaryPanel: {
    marginBottom: "1.5rem",
  },
  summaryTitle: {
    marginBottom: "1.25rem",
    fontSize: "1.125rem",
    lineHeight: "calc(1.75 / 1.125)",
    fontWeight: 700,
  },
  summaryCard: {
    borderRadius: "1rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.bd6,
    backgroundColor: tokens.surf2,
    padding: "1rem",
  },
  summaryRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: "1rem",
  },
  summaryImage: {
    height: "4rem",
    width: "4rem",
    flexShrink: 0,
    objectFit: "contain",
  },
  summaryBody: {
    minWidth: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  summaryNameRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.5rem",
  },
  summaryName: {
    fontSize: "1rem",
    lineHeight: "calc(1.5 / 1)",
    fontWeight: 700,
    color: tokens.text,
  },
  movesRow: {
    marginTop: "0.5rem",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    columnGap: "0.75rem",
    rowGap: "0.25rem",
    fontSize: "0.75rem",
    lineHeight: "calc(1 / 0.75)",
  },
  muted40: {
    color: tokens.tx40,
  },
  emptyMove: {
    cursor: "default",
    borderRadius: "9999px",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: tokens.bd10,
    paddingInline: "0.5rem",
    paddingBlock: "0.125rem",
    fontSize: "11px",
    color: tokens.tx20,
  },
  metaRow: {
    marginTop: "0.375rem",
    display: "flex",
    flexWrap: "wrap",
    columnGap: "1rem",
    rowGap: "0.25rem",
    fontSize: "11px",
  },
  tooltipTitle: {
    marginBottom: "0.25rem",
    display: "block",
    fontWeight: 600,
    color: tokens.text,
  },
  tooltipText: {
    color: tokens.text,
  },
  inlineTrigger: {
    display: "inline-flex",
    alignItems: "baseline",
    gap: "0.25rem",
  },
  muted70: {
    color: tokens.tx70,
  },
});
